apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dev
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: 10.107.185.142:8082/node-app-k8s
      imagePullSecrets:
        - name: nexus-docker
        