apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: dev
  labels:
    app: mysql-pod
spec:
  containers:
  - name: mysql
    image: mysql
    envFrom:
      secretKeyRef:
        name: mysql-cred

    ports:
    - containerPort: 3306