apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app-container
        image: abdelrahmankha/node-app:1.1

        envFrom:
        - configMapRef:
            name: app-conf

        - secretRef:
            name: app-sec

        ports:
        - containerPort: 3000